# Generated by Django 5.0.2 on 2024-03-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, verbose_name='текст поста'),
        ),
    ]
