# Generated by Django 5.0.2 on 2024-03-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.URLField(max_length=500, null=True, verbose_name='иконка'),
        ),
    ]
