# Generated by Django 5.0.2 on 2024-03-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_tag_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.IntegerField(null=True, verbose_name='порядок'),
        ),
    ]
