# Generated by Django 5.0.2 on 2024-03-10 19:50

import posts.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_tag_options_alter_tag_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=posts.service.get_path_for_icon, verbose_name='иконка'),
        ),
    ]
