# Generated by Django 5.0.2 on 2024-03-11 09:10

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='default/avatar.png', null=True, upload_to=users.models.get_path_for_avatar, verbose_name='аватар')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('email', models.EmailField(max_length=60, null=True, unique=True, verbose_name='почта')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='местоположение')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='биография')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
